repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        always_run: true
        pass_filenames: true
        files: ^.*\.py$
      - id: generate passthrough modules
        name: generate passthrough modules
        entry: python scripts/generate_version_submodule_imports.py generate
        language: system
        always_run: true
        pass_filenames: false
      - id: generate json schemas
        name: generate json schemas
        entry: python scripts/generate_json_schemas.py
        language: system
        always_run: true
        pass_filenames: false
      - id: generate spec md docs
        name: generate spec md docs
        entry: python scripts/generate_spec_documentation.py
        language: system
        always_run: true
        pass_filenames: false
