repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        always_run: true
        pass_filenames: true
        files: ^.*\.py$
      - id: generate passthrough modules
        name: generate passthrough modules
        entry: python scripts/generate_version_submodule_imports.py generate
        language: system
        always_run: true
        pass_filenames: false
      - id: generate json schemas
        name: generate json schemas
        entry: python scripts/generate_json_schema.py
        language: system
        always_run: true
        pass_filenames: false
      - id: generate spec md docs
        name: generate spec md docs
        entry: python scripts/generate_spec_documentation.py
        language: system
        always_run: true
        pass_filenames: false
