# Auto-generated by generate_passthrough_modules.py - do not modify

from .v0_4.raw_nodes import *

# * imports don't include classes prefixed with _ so we need to explicitly import the * classes we need here
from .v0_4.raw_nodes import _WeightsEntryBase
