{% set pyproject = load_file_data('pyproject.toml') %}
{% set version_match = load_file_regex(
  load_file="src/bioimageio/spec/_version.py",
  regex_pattern='VERSION = "(.+)"') %}
{% set version = version_match[1] %}

package:
  name: {{ pyproject['project']['name'] }}
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep.lower().replace('email-validator', 'email_validator') }}
    {% endfor %}

build:
  noarch: python
  number: 0
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - {{ pyproject['project']['name'] }}
  source_files:
    - tests
    - example_descriptions
  requires:
    {% for dep in pyproject['project']['optional-dependencies']['dev'] %}
    {% if not dep.startswith('griffe')  %}
    - {{ dep.lower().replace('torch', 'pytorch').replace('huggingface-hub', 'huggingface_hub') }}
    {% endif %}
    {% endfor %}
  commands:
    - pytest --capture=no

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: bioimage.io specifications package
  license: MIT
  license_file: LICENSE
