# possibly superseded by recipe.yaml
# TODO: decide for package builder and clean up
{% set setup_py_data = load_setup_py_data() %}

package:
  name: bioimageio.spec
  version: {{ setup_py_data['version'] }}

source:
  path: ..

requirements:
  build:
    - python >=3.8,<3.13
    - pip
  run:
    - python >=3.8,<3.13
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bioimageio.spec
  source_files:
    - tests
    - example_descriptions
  requires:
    {% for dep in setup_py_data['extras_require']['dev'] %}
    {% if dep not in ('json_schema_for_humans',): %}
    - {{ dep.replace('torch', 'pytorch').lower() }}
    {% endif %}
    {% endfor %}
  commands:
    - pytest -n auto --capture=no

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: bioimage.io specifications package
  license: MIT
  license_file: LICENSE
