{% set pyproject = load_file_data('pyproject.toml') %}
{% set version_match = load_file_regex(
  load_file="bioimageio/spec/__init__.py",
  regex_pattern='^__version__ = "(.+)"') %}
{% set version = version_match[1] %}

package:
  name: {{ pyproject['project']['name'] }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python {{ pyproject['project']['requires-python'] }}
    - pip
  run:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}


build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - {{ pyproject['project']['name'] }}
  source_files:
    - tests
    - example_descriptions
  requires:
    {% for dep in pyproject['project']['optional-dependencies']['dev'] %}
    - {{ dep.replace('torch', 'pytorch').lower().replace('_', '-') }}
    {% endfor %}
  commands:
    - pytest --capture=no

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: bioimage.io specifications package
  license: MIT
  license_file: LICENSE
