{% set setup_py_data = load_setup_py_data() %}

package:
  name: bioimageio.spec
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..
  git_url: ..

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  entry_points:
    {% for ep in setup_py_data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bioimageio.spec
  source_files:
    - tests
    - example_specs
  requires:
    {% for dep in setup_py_data['extras_require']['test'] %}
    - {{ dep.replace('torch', 'pytorch').lower() }}
    {% endfor %}
  commands:
    - pytest .

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: BioImage.IO Spec Validator and specifications package
  license: MIT
  license_file: LICENSE
